algoblog/urls.py
from django.urls import path
from . import views


app_name = 'algoblog'


urlpatterns = [
# post views
    path('', views.AlgoBlogListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>', views.AlgoBlogDetailView.as_view(), name='post_detail'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactFormView.as_view(),name='contact'),
    path('success/', views.ContactSuccessView.as_view(),name='success'),


    #path('<slug:post>/', views.AlgoBlogDetailView.as_view(), name='post_detail'),

]

algoritmi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('algoblog.urls')),
    path('tinymce/',include('tinymce.urls')), # new
]

algoblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.






class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


            


class Post(models.Model):
        STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        )
        DIFFICULTY_LEVEL_CHOICES = [
        ('easy','Easy'),
        ('medium','Medium'),
        ('hard','Hard'),
        ]
        title = models.CharField(max_length=250)
        
        slug = models.SlugField(max_length=250,unique_for_date='publish')
        author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
        body = models.TextField()
        task_link = models.URLField(max_length=200, blank=True)
        body_code = models.TextField(blank=True)
        publish = models.DateTimeField(default=timezone.now)
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        status = models.CharField(max_length=10,choices=STATUS_CHOICES, default='draft')
        difficulty = models.CharField(max_length=6,choices=DIFFICULTY_LEVEL_CHOICES, default='easy')

        class Meta:
            ordering = ('-publish',)


        def __str__(self):
            return self.title

        def get_absolute_url(self):
            return reverse('algoblog:post_detail',args=[self.publish.year,self.publish.month, self.publish.day, self.slug])
            #return reverse('algoblog:post_detail',args=[self.slug])



        objects = models.Manager() # The default manager.
        published = PublishedManager() # Our custom manager.
            

algoblog/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

# class SendMailForm(forms.Form):
#     name = forms.CharField(max_length=25)
#     email = forms.EmailField()
#     message = forms.CharField(widget=forms.Textarea)


class ContactForm(forms.Form):

    name = forms.CharField(max_length=120,required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=100,required=True)
    message = forms.CharField(widget=forms.Textarea)

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """

        clean_data= super().clean()

        name = clean_data.get('name').strip()
        from_email =  clean_data.get('email').strip()
        subject = clean_data.get('subject')

        message = f'{name} with email {from_email} said:'
        message += f'\n"{subject}"\n\n'
        message += clean_data.get('message')


        return subject, message


    def send(self):
        subject, message = self.get_info()


        send_mail(
            subject= subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS]



        )

algoblog/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, TemplateView, FormView

from .forms import ContactForm

from .models import Post

from django.urls import reverse_lazy



# Create your views here.

class AlgoBlogListView(ListView):
    model = Post 

    template_name = 'algoblog/post/list.html' 
    def get_context_data(self, **kwargs):
        context = super(AlgoBlogListView, self).get_context_data(**kwargs)
        context['latest_algorithm'] = Post.objects.all()[:1]
        return context 

class AlgoBlogDetailView(DetailView):
    model = Post
    # slug_field = 'slug'
    # slug_url_kwarg = 'slug'
    template_name = 'algoblog/post/detail.html'
    def get_context_data(self, *args, **kwargs):
        context = super(AlgoBlogDetailView, self).get_context_data(*args, **kwargs)
        context['link_list'] = Post.objects.all()
        return context


class AboutView(TemplateView):
    template_name = 'algoblog/post/about.html'    

# class ContactView(TemplateView):
#     template_name = 'algoblog/post/contact.html'    

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'algoblog/post/contact.html'    
    success_url = reverse_lazy('algoblog:success')


    def form_valid(self, form):
        #calls custom send method from forms.py
        form.send()
        return super().form_valid(form)


# contact/views.py
class ContactSuccessView(TemplateView):
    template_name = 'algoblog/post/success.html'

algoblog/templates/algoblog/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://kit.fontawesome.com/e5e5503423.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>


    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body>


    <div class="wrapper">

                                        <header>
                                            <h1>Algorithms and stuff..</h1>

                                            <h3>My solutions to various problems</h3>

                                            <div class="menu">
                                                <a href="{% url 'algoblog:post_list' %}">HOME</a>
                                                <a href="{% url 'algoblog:about' %}">ABOUT</a>
                                                <a href="{% url 'algoblog:contact' %}">CONTACT</a>
                                            </div>
                                            
                                            
                                        </header>
                                    
                                    {% block content %}
                                    
                                    {% endblock %}

<!-- 
    wrapper end                             -->
    </div>
                                    
                                
                                <footer class="site-footer">
                                    <div class="container1">
                                                
                                                    <div class="about">
                                                            <h6>Hello there!</h6>
                                                            <!-- <p> <i> My name is Ivan Urban </i>      </p> -->
                                                            <p>I am a full stack developer. 
                                                                I like  web development, coding puzzles, algorithms and photography. </p>
                                                        
                                                    </div>


                                                    <div class="footer-contact">

                                                        <div class="inner-contact">
                                                                    <h6>Contact</h6>
                                                                            
                                                                    <!-- <p><img src="{% static 'img/mail.png'%}" width="20" height="20" alt="">ivanurban_bg@yahoo.com  </p> -->
                                                                    <p id="email"><span><i class="far fa-envelope"></i>&nbsp;</span>ivanurban_bg@yahoo.com </p>


                                                                    
                                                                    <p><span><i class='fas fa-phone'></i>&nbsp;</span>011/123-4567</p>


                                                        </div>
                                            


                                                    </div>

                                    
                                                
                                                
                                            
                                    </div>

                                    <hr>

                                    <div class="container2">
                                        
                                            
                                                    <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by 
                                                        <a href="#">Gradski</a>.
                                                    </p>
                                                          

                                                        <div class="soc_icons">

                                                            <a href="#"  ><img src="{% static 'img/linkedin.svg' %}"  width="40" height="40"></a> 
                                                            <a href="#"  ><img src="{% static 'img/hackerrank.svg' %}"  width="40" height="40"></a>
                                                      


                                                        </div>
                                                 

                                                       

                                                        


                                          
                                                            
                                                
                                    </div>

                                </footer> 



      



<script>

document.getElementsByTagName("pre")[0].classList.add("prettyprint");
</script>

</body>
</html>

algoblog/templates/algoblog/post/about.html
{% extends "algoblog/base.html" %}

{% load static %}

{% block content %}


<div class="container-about">



    <div class="container">

   

                    <div class="posts">

                        

                                    <h1 class="title">Hi</h1>
                    
                    
                    
                                    My Name is Ivan Urban, I am a full stack developer. 
                                    I have a vast experience with a lot of different technologies.
                                     I am proficient in python/django, javascript, css, html, databases.
                                      I like coding challenges, algorithms and photography. 
                                    I am experienced IT guy that worked in different positions through his career
                                    
                                

                </div>

             
    </div>
  





</div>
 

{% endblock %}

algoblog/templates/algoblog/post/contact.html
{% extends "algoblog/base.html" %}

{% load static %}

{% load widget_tweaks %}

{% block content %}



    <div class="contact-container">

<!-- 
            <div class="contact-text">

                <h2>Contact me</h2>
                <p>Feel free to get in touch with me. I am always open to discussing...</p>

                <p>mail icon</p>
                <p>ivanurban_bg@yahoo.com</p>

                <p>phone icon</p>
                <p>+381621693170</p>
            </div>

            <div class="contact-email">
                <h4>Send me an Email</h4>
                
                <div class="email-form">
                    <form method="post">
                        {% csrf_token %}
                        <table>
                            {{ form.as_table  }}
                        </table>
                            <button id="sendMailButton" type="submit">Submit</button>
                        </form>
                </div>
                
           </div> -->


                                    
                                        



<div class="container">





    <div class="posts">

        
    
                                            

                        <h1 class="title">Send me an email</h1>
            
                
                    <div class="contact-email">
                        <!-- <h4>Send me an Email</h4> -->
                        
                        <div class="email-form">
                            <form method="post">
                            
                                {% csrf_token %}

                                <!-- {{ form.as_p }}
                                 -->
                                <div class="form-group">
                                   
                                    
                                    {% render_field form.name class="form-control-text"  placeholder="Name" type="text" %}
                                  </div>
                                    
                           
                
                                  <div class="form-group">
                                  
                                    {% render_field form.email class="form-control-text"  placeholder="Email" %}
                                  </div>
                                    

                                
                                  <div class="form-group">
                                  
                                    {% render_field form.subject class="form-control-text"  placeholder="Subject" %}
                                  </div>

                                  <div class="form-group">
                                 
                                    {% render_field form.message  class="form-control-textarea" placeholder="Message" %}
                                  </div>
                                    
                                  <div class="form-group">
                                    <button type="submit" id="sendMailButton"  value="Submit" > Submit </button>
                                  </div>
                         
                                   
                               
                                     <!-- <button id="sendMailButton" type="submit">Submit</button> -->
                                </form>
                        </div>
                        
                </div>
        
                    
                

</div>


</div>


</div>


{% endblock %}

algoblog/templates/algoblog/post/detail.html
{% extends "algoblog/base.html" %}

{% load static %}

{% block content %}

<div class="container">


            <div class="links">
                {% for l in link_list%}


                        <a href="{{ l.get_absolute_url }}">

                            {{ l.title }}


                        </a>


                {% endfor %}


            </div>

            <div class="posts">



                        <h1 class="title">{{ post.title }}</h1>

                        <div class="date">


                        Published by {{ post.author }}
                        <!-- 
                                        {{ post.publish }} -->

                                       

                        </div>

                        

                        <div class="difficulty-level">

                            Difficulty: {{ post.difficulty }}


                    </div>

                        {% with body=post.body|safe %}



                        
                        <div class="post-body">

                            {{ body }}

                        </div>
                                                                                
                        {% endwith %}

                        

            </div>


</div>


{% endblock %}

algoblog/templates/algoblog/post/list.html
{% extends "algoblog/base.html" %}

{% load static %}

{% block content %}


     



        <div class="container">

                <div class="links">

                        {% for post in object_list %}

                                <a href="{{ post.get_absolute_url }}">

                                    {{ post.title }}


                                </a>

                        {% endfor %}
                </div>



                <div class="posts">

                        {% for l in latest_algorithm %}

                                <h1 class="title">{{ l.title }}</h1>
                
                                <div class="date">
                
                
                                Published by {{ l.author }}
                                <!-- 
                                                {{ post.publish }} -->
                                
                                            
                
                                </div>
                

                                <div class="difficulty-level">

                                        Difficulty: {{ l.difficulty }}


                                </div>

                                {% with body=l.body|safe %}

                        <!-- <div class="post-body"> -->

                                {{ body }}

                        <!-- </div> -->
                
                              
                                
                                {% endwith %}
                
                       {% endfor %}
            
                            

            </div>
        
        
</div>
          





{% endblock %}

algoblog/templates/algoblog/post/success.html
{% extends "algoblog/base.html" %}

{% load static %}


{% block content %}


<div class="success">

    <h1>Your message is sent</h1>
    <p>You can send another in the <a href="{% url 'algoblog:contact' %}">contact page</a></p>


</div>
 
    

{% endblock %}